import { getStore } from "@netlify/blobs";

// ---- Config (all overridable via Netlify environment variables) ----
const MODEL = process.env.ANTHROPIC_MODEL || "claude-3-5-haiku-latest";
const MAX_TEXT_LEN = 600;
const MAX_IMAGE_BASE64_BYTES = 4 * 1024 * 1024; // ~4MB of base64 (~3MB actual image)
const PER_IP_HOURLY_LIMIT = parseInt(process.env.AI_ROOM_IP_HOURLY_LIMIT || "5", 10);
const GLOBAL_DAILY_LIMIT = parseInt(process.env.AI_ROOM_GLOBAL_DAILY_LIMIT || "100", 10);

const WALL_COLORS = ["white", "sand", "sage", "slate blue", "charcoal"];
const ACCENT_COLORS = ["terracotta", "navy", "forest", "plum", "black", "ivory"];

function jsonResponse(status, body) {
  return new Response(JSON.stringify(body), {
      status,
          headers: { "content-type": "application/json" },
            });
            }

            export default async (req, context) => {
              if (req.method !== "POST") {
                  return jsonResponse(405, { error: "Method not allowed" });
                    }

                      const apiKey = process.env.ANTHROPIC_API_KEY;
                        if (!apiKey) {
                            // Lets the frontend fall back to the local keyword-matching demo instead of hard failing.
                                return jsonResponse(503, { error: "AI is not configured on this deploy yet." });
                                  }

                                    let body;
                                      try {
                                          body = await req.json();
                                            } catch {
                                                return jsonResponse(400, { error: "Invalid request body." });
                                                  }

                                                    const text = (body.text || "").toString().slice(0, MAX_TEXT_LEN);
                                                      const photoBase64 = body.photoBase64 ? String(body.photoBase64) : null;
                                                        const photoMediaType = body.photoMediaType ? String(body.photoMediaType) : "image/jpeg";

                                                          if (!text && !photoBase64) {
                                                              return jsonResponse(400, { error: "Describe the room or upload a photo first." });
                                                                }
                                                                  if (photoBase64 && photoBase64.length > MAX_IMAGE_BASE64_BYTES) {
                                                                      return jsonResponse(413, { error: "That photo is too large. Try a smaller image." });
                                                                        }
                                                                          if (photoBase64 && !/^image\/(jpeg|png|webp)$/.test(photoMediaType)) {
                                                                              return jsonResponse(400, { error: "Photo must be a JPEG, PNG, or WebP image." });
                                                                                }

                                                                                  // ---- Rate limiting (approximate; good enough for a public demo, not a billing-grade limiter) ----
                                                                                    const store = getStore("ai-room-limits");
                                                                                      const ip =
                                                                                          context.ip ||
                                                                                              req.headers.get("x-nf-client-connection-ip") ||
                                                                                                  req.headers.get("x-forwarded-for") ||
                                                                                                      "unknown";
                                                                                                        const now = new Date();
                                                                                                          const hourKey = `ip:${ip}:${now.toISOString().slice(0, 13)}`; // yyyy-mm-ddThh
                                                                                                            const dayKey = `global:${now.toISOString().slice(0, 10)}`; // yyyy-mm-dd
                                                                                                            
                                                                                                              const [ipCountRaw, globalCountRaw] = await Promise.all([store.get(hourKey), store.get(dayKey)]);
                                                                                                                const ipCount = parseInt(ipCountRaw || "0", 10);
                                                                                                                  const globalCount = parseInt(globalCountRaw || "0", 10);
                                                                                                                  
                                                                                                                    if (ipCount >= PER_IP_HOURLY_LIMIT) {
                                                                                                                        return jsonResponse(429, {
                                                                                                                              error: `You've hit the demo limit (${PER_IP_HOURLY_LIMIT}/hour). Try again in a bit.`,
                                                                                                                                  });
                                                                                                                                    }
                                                                                                                                      if (globalCount >= GLOBAL_DAILY_LIMIT) {
                                                                                                                                          return jsonResponse(429, {
                                                                                                                                                error: "The AI demo has reached its usage limit for today. Try again tomorrow.",
                                                                                                                                                    });
                                                                                                                                                      }
                                                                                                                                                      
                                                                                                                                                        // ---- Build the Claude request ----
                                                                                                                                                          const userContent = [];
                                                                                                                                                            if (text) userContent.push({ type: "text", text });
                                                                                                                                                              if (photoBase64) {
                                                                                                                                                                  userContent.push({
                                                                                                                                                                        type: "image",
                                                                                                                                                                              source: { type: "base64", media_type: photoMediaType, data: photoBase64 },
                                                                                                                                                                                  });
                                                                                                                                                                                    }
                                                                                                                                                                                    
                                                                                                                                                                                      const tool = {
                                                                                                                                                                                          name: "set_room",
                                                                                                                                                                                              description: "Set the 3D preview room's dimensions and colors based on the user's description and/or photo.",
                                                                                                                                                                                                  input_schema: {
                                                                                                                                                                                                        type: "object",
                                                                                                                                                                                                              properties: {
                                                                                                                                                                                                                      width_ft: { type: "number", minimum: 4, maximum: 40 },
                                                                                                                                                                                                                              depth_ft: { type: "number", minimum: 4, maximum: 40 },
                                                                                                                                                                                                                                      height_ft: { type: "number", minimum: 6, maximum: 20 },
                                                                                                                                                                                                                                              wall_color: { type: "string", enum: WALL_COLORS },
                                                                                                                                                                                                                                                      counter_color: { type: "string", enum: ACCENT_COLORS },
                                                                                                                                                                                                                                                              island_color: { type: "string", enum: ACCENT_COLORS },
                                                                                                                                                                                                                                                                      has_island: { type: "boolean" },
                                                                                                                                                                                                                                                                              notes: { type: "string", description: "Short (<15 word) human-readable summary of what was applied." },
                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                          required: ["width_ft", "depth_ft", "height_ft", "wall_color", "has_island", "notes"],
                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                  let claudeRes;
                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                        claudeRes = await fetch("https://api.anthropic.com/v1/messages", {
                                                                                                                                                                                                                                                                                                              method: "POST",
                                                                                                                                                                                                                                                                                                                    headers: {
                                                                                                                                                                                                                                                                                                                            "content-type": "application/json",
                                                                                                                                                                                                                                                                                                                                    "x-api-key": apiKey,
                                                                                                                                                                                                                                                                                                                                            "anthropic-version": "2023-06-01",
                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                        body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                model: MODEL,
                                                                                                                                                                                                                                                                                                                                                                        max_tokens: 400,
                                                                                                                                                                                                                                                                                                                                                                                tools: [tool],
                                                                                                                                                                                                                                                                                                                                                                                        tool_choice: { type: "tool", name: "set_room" },
                                                                                                                                                                                                                                                                                                                                                                                                messages: [
                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                      role: "user",
                                                                                                                                                                                                                                                                                                                                                                                                                                  content: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                type: "text",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "You're configuring a simple 3D room preview for a home-renovation website. Based on the description and/or photo below, call set_room with reasonable dimensions (in feet) and colors chosen from the allowed values. If something isn't mentioned, make a sensible default rather than skipping it.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...userContent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error("ai-room: fetch to Anthropic failed", err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return jsonResponse(502, { error: "Couldn't reach the AI service. Try again." });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!claudeRes.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const errText = await claudeRes.text();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error("ai-room: Anthropic API error", claudeRes.status, errText);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return jsonResponse(502, { error: "The AI service returned an error." });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const data = await claudeRes.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const toolUse = (data.content || []).find((b) => b.type === "tool_use" && b.name === "set_room");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!toolUse) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return jsonResponse(502, { error: "Couldn't make sense of that input. Try rephrasing." });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Best-effort counters — not atomic, fine for a soft usage cap on a demo feature.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await Promise.all([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      store.set(hourKey, String(ipCount + 1)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          store.set(dayKey, String(globalCount + 1)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return jsonResponse(200, { result: toolUse.input });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export const config = { path: "/api/ai-room" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
